[package]
name = "woordeskat"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["colored"]

[dependencies]
rand = "0.8.4"
levenshtein = "1.0.5"
colored = { version = "2.0.0", optional = true }